# 指定撰写格式。 支持的版本有：2.x、3.x
version: "3.9"

# 允许服务相互通信的层。
networks:
  # 自定义的网络名称
  soil:
    # 指定该网络应使用哪个驱动程序。
    driver: bridge

# 服务是应用程序中计算资源的抽象定义，可以独立于其他组件进行扩展/替换。
services:
  soil-redis:
    # 覆盖容器映像声明的默认命令（即通过 Dockerfile 的 CMD）。
    command: >
      bash -c '
        chmod +x /usr/local/bin/healthcheck.sh;
        redis-server /path/to/redis.conf;
      '
    # 指定自定义容器名称，而不是生成的默认名称。
    container_name: soil-redis
    # 声明运行以确定该服务的容器是否“健康”的检查。
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      # 运行状况检查将在容器启动后首先运行间隔秒，然后在之前的每个检查完成后再次运行间隔秒。
      interval: 10s
      # 如果单次运行检查花费的时间超过超时秒数，则检查被视为失败。
      timeout: 10s
      # 需要重试健康检查连续失败才能将容器视为不健康。
      retries: 3
      # 为需要时间引导的容器提供初始化时间。
      start_period: 40s
    # 声明用于服务容器的自定义主机名。
    hostname: soil-redis
    # 指定启动容器的图像。
    image: redis:7.0.12
    # 定义服务容器附加到的网络，引用顶级网络键下的条目。
    networks:
      - soil
    # 暴露端口。 指定两个端口 (HOST:CONTAINER)，或仅指定容器端口（选择临时主机端口）。
    ports:
      - "6379:6379"
    # 定义平台在容器终止时应用的策略。
    restart: always
    # 定义服务容器必须可以访问的挂载主机路径或命名卷。
    volumes:
      - ./docker/redis/conf/redis.conf:/path/to/redis.conf
      - ./docker/redis/sh/healthcheck.sh:/usr/local/bin/healthcheck.sh
      - ./docker/redis/data:/etc/redis/data
  soil-elasticsearch:
    # 指定自定义容器名称，而不是生成的默认名称。
    container_name: soil-elasticsearch
    # 定义容器中设置的环境变量。
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      DISCOVERY: single-node
    # 声明运行以确定该服务的容器是否“健康”的检查。
    healthcheck:
      test: ["CMD-SHELL", "curl -k -u elastic:${ELASTIC_PASSWORD} https://localhost:9200/_cat/health?h=status | grep -q '[(green)(yellow)]'"]
      # 运行状况检查将在容器启动后首先运行间隔秒，然后在之前的每个检查完成后再次运行间隔秒。
      interval: 10s
      # 如果单次运行检查花费的时间超过超时秒数，则检查被视为失败。
      timeout: 10s
      # 需要重试健康检查连续失败才能将容器视为不健康。
      retries: 3
      # 为需要时间引导的容器提供初始化时间。
      start_period: 40s
    # 声明用于服务容器的自定义主机名。
    hostname: soil-elasticsearch
    # 指定启动容器的图像。
    image: elasticsearch:${STACK_VERSION}
    # 定义服务容器附加到的网络，引用顶级网络键下的条目。
    networks:
      - soil
    # 暴露端口。 指定两个端口 (HOST:CONTAINER)，或仅指定容器端口（选择临时主机端口）。
    ports:
      - "9200:9200"
      - "9300:9300"
    # 定义平台在容器终止时应用的策略。
    restart: always
  soil-kibana:
    # 指定自定义容器名称，而不是生成的默认名称。
    container_name: soil-kibana
    # 表示服务之间的启动和关闭依赖关系。
    depends_on:
      soil-elasticsearch:
        condition: service_healthy
    # 定义容器中设置的环境变量。
    environment:
      I18N_LOCALE: zh-CN
      SERVER_PUBLICBASEURL: http://soil-kibana:5601
    # 声明运行以确定该服务的容器是否“健康”的检查。
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601/api | grep -q 'HTTP/1.1 200 OK'"]
      # 运行状况检查将在容器启动后首先运行间隔秒，然后在之前的每个检查完成后再次运行间隔秒。
      interval: 10s
      # 如果单次运行检查花费的时间超过超时秒数，则检查被视为失败。
      timeout: 10s
      # 需要重试健康检查连续失败才能将容器视为不健康。
      retries: 3
      # 为需要时间引导的容器提供初始化时间。
      start_period: 40s
    # 声明用于服务容器的自定义主机名。
    hostname: soil-kibana
    # 指定启动容器的图像。
    image: kibana:${STACK_VERSION}
    # 定义服务容器附加到的网络，引用顶级网络键下的条目。
    networks:
      - soil
    # 暴露端口。 指定两个端口 (HOST:CONTAINER)，或仅指定容器端口（选择临时主机端口）。
    ports:
      - "5601:5601"
    # 定义平台在容器终止时应用的策略。
    restart: always
  soil-logstash:
    # 指定自定义容器名称，而不是生成的默认名称。
    container_name: soil-logstash
    # 表示服务之间的启动和关闭依赖关系。
    depends_on:
      soil-elasticsearch:
        condition: service_healthy
    # 定义容器中设置的环境变量。（源于日志提示）
    environment:
      xpack.monitoring.enabled: true
    # 声明运行以确定该服务的容器是否“健康”的检查。
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node | grep -q '\"status\":\"green\"'"]
      # 运行状况检查将在容器启动后首先运行间隔秒，然后在之前的每个检查完成后再次运行间隔秒。
      interval: 10s
      # 如果单次运行检查花费的时间超过超时秒数，则检查被视为失败。
      timeout: 10s
      # 需要重试健康检查连续失败才能将容器视为不健康。
      retries: 3
      # 为需要时间引导的容器提供初始化时间。
      start_period: 40s
    # 声明用于服务容器的自定义主机名。
    hostname: soil-logstash
    # 指定启动容器的图像。
    image: logstash:${STACK_VERSION}
    # 定义服务容器附加到的网络，引用顶级网络键下的条目。
    networks:
      - soil
    # 暴露端口。 指定两个端口 (HOST:CONTAINER)，或仅指定容器端口（选择临时主机端口）。
    ports:
      - "5044:5044"
      - "9600:9600"
    # 定义平台在容器终止时应用的策略。
    restart: always
    # 定义服务容器必须可以访问的挂载主机路径或命名卷。
    volumes:
      - /docker/elastic/logstash/logs:/usr/share/logstash/logs
  soil-backend:
    # 指定用于从源创建容器映像的构建配置。
#    build:
#      # 包含 Dockerfile 的目录的路径，或 git 存储库的 url。
#      context: ./docker/soil-backend
#      # Compose 使用备用文件进行构建。 还必须指定构建路径。
#      dockerfile: Dockerfile
    # 指定自定义容器名称，而不是生成的默认名称。
    container_name: soil-backend
    # 表示服务之间的启动和关闭依赖关系。
    depends_on:
      soil-redis:
        condition: service_healthy
      soil-elasticsearch:
        condition: service_healthy
    # 声明运行以确定该服务的容器是否“健康”的检查。
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/actuator/health | grep -q '^{\"status\":\"UP\"'"]
      # 运行状况检查将在容器启动后首先运行间隔秒，然后在之前的每个检查完成后再次运行间隔秒。
      interval: 10s
      # 如果单次运行检查花费的时间超过超时秒数，则检查被视为失败。
      timeout: 10s
      # 需要重试健康检查连续失败才能将容器视为不健康。
      retries: 3
      # 为需要时间引导的容器提供初始化时间。
      start_period: 40s
    # 声明用于服务容器的自定义主机名。
    hostname: soil-backend
    # 指定启动容器的图像。
    image: soil-backend:0.0.1-SNAPSHOT
    # 定义服务容器附加到的网络，引用顶级网络键下的条目。
    networks:
      - soil
    # 暴露端口。 指定两个端口 (HOST:CONTAINER)，或仅指定容器端口（选择临时主机端口）。
    ports:
      - "8080:8080"
    # 定义平台在容器终止时应用的策略。
    restart: always
  soil-nginx:
    # 指定自定义容器名称，而不是生成的默认名称。
    container_name: soil-nginx
    # 表示服务之间的启动和关闭依赖关系。
    depends_on:
      soil-backend:
        condition: service_healthy
    # 声明运行以确定该服务的容器是否“健康”的检查。
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80 | grep -q '<!doctype html>'"]
      # 运行状况检查将在容器启动后首先运行间隔秒，然后在之前的每个检查完成后再次运行间隔秒。
      interval: 10s
      # 如果单次运行检查花费的时间超过超时秒数，则检查被视为失败。
      timeout: 10s
      # 需要重试健康检查连续失败才能将容器视为不健康。
      retries: 3
      # 为需要时间引导的容器提供初始化时间。
      start_period: 40s
    # 声明用于服务容器的自定义主机名。
    hostname: soil-nginx
    # 指定启动容器的图像。
    image: nginx:1.25.1
    # 定义服务容器附加到的网络，引用顶级网络键下的条目。
    networks:
      - soil
    # 暴露端口。 指定两个端口 (HOST:CONTAINER)，或仅指定容器端口（选择临时主机端口）。
    ports:
      - "80:80"
    # 定义平台在容器终止时应用的策略。
    restart: always
    # 定义服务容器必须可以访问的挂载主机路径或命名卷。
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/docs/html:/etc/nginx/docs/html